### ISSUE TITLE
Create wireframe for customer's pet section.

### ISSUE THREAD

**Issue by navx2810** [navx2810/gbs-grm#3]
The pet section is where the customers will manage and view the details of all their pets. They need:

- [x] a way to add, update and remove pets.
- [x] a way to see the pets name, breed, gender for each pet.
- [x] a way to click on the pet and view additional details, which is a separate design.
- [x] a way to view past, and upcoming appoints for their pets.

**Comment by Aphemra** [comment]
I'll work on this.

**Comment by Aphemra** [comment]
360px Portrait 640px Landscape.
768px Portrait 1024px Landscape.

For reference, these are the sizes to be designed for.

**Comment by navx2810** [comment]
Yes. For now, we can't make too many assumptions on what device users will access the app with. A groomer's customers, and employees can be anyone. Young - old, Rich - poor, Intelligent - dunce.

**Comment by Aphemra** [comment]
@navx2810 Is there any specific information that needs to be shown for past and current appointments besides the date and time?

**Comment by Aphemra** [comment]
This is what I have so far.
![customer-pet-section-wireframe-320x640](https://user-images.githubusercontent.com/17531367/27479075-3dd3dd40-57e0-11e7-9a60-edec7d0f5489.png)

**Comment by navx2810** [comment]
Nic. I've had some time to review it. Here's my input.

I can't imagine why the customer would need to see their pet's tags. Those tags are specifically for the groomer to let them know about an animal's conditions. If someone's precious puppy is labeled a biter and a pisser, the customer might not be to happy seeing that.

Does the customer need to see both their Upcoming and past appointments at once? I can't see a reason or situation where I would want that information at the same time. Maybe consider making it one list, but a switch for [Past] / [Upcomming] Appointments.

Would the customer ever need a reason to move their pets up and down the list? Is it listed in priority or something? I can't ever see a reason why someone would have more than 10 pets, so it's almost useless to have any sorting, moving, or filtering capabilities. Maybe turn the arrows into a trash icon?

Right now, the pet card does not contain all the data on the pet, (as it was designed), it needs a way to navigate to a "details" "see more" section. Consider replacing "edit" with details. The user wouldn't edit their pet unless they saw the full form of information, which wouldn't be on that small card layout. My train of logic is that the user would most likely click on more details, before they would want to edit.

If any of this feedback seems odd, or you have different ideas on solving the problem, please drop a comment. Don't take my suggestions as law, but as merely considerations.

**Comment by navx2810** [comment]
Also something to consider, the add a pet is at the bottom of the appointments. I would consider moving that space above the appointments so it's under the list of pets, and changing the space "add pet" is to "add appointment"

**Comment by navx2810** [comment]
If you do decide on removing the icon pallet, there will be a lot of empty space that could be used for something. Maybe a next appointment timestamp? Any ideas?

**Comment by Aphemra** [comment]
The Appointments window is a drop down for each pet accessed by the black arrow under the edit button (which is a drop down button, not a re-order button. Not sure if that's intuitive enough I suppose).

Removing the icon section would give more room. The upcoming appointment idea might work depending on what information for upcoming appointments is required.

In the appointment drop down, I was planning to have the individual appointment dates being clickable/tappable and would take you to the actual calendar slot.

Making the Upcoming and Past appointments under the drop down two separate things that can be switched between (kind of like tabs) might look better but it might also be too many clicks/taps. Though if we take into account customers will most likely want to see upcoming appointments first and foremost, hiding the past appointments under one extra click shouldn't hurt the UX.

Changing edit to more details could work well and inputting the edit button within that section.

What about changing the black arrow to "Appointments" and edit to "More details" which are two separate drop down sections. It could save some clicks and allow for the customer to see the details of their pet before moving to a new window/screen to edit it in what will be the "New Pet" form but with the current inputted pet information pre-added so they can be edited as needed and resaved easily.

Not sure if a trash icon is needed on this main design as that can be hid within the edit function... I imagine it wouldn't be something customers need readily available on the main screen and can be hidden a bit.

To reiterate in case it wasn't clear, The Add Pet button isn't under the appointments if the appointment drop down is closed. So I think that's fine where it is since it makes sense when the drop down is compressed as opposed to open. Its open in the wireframe to show that it exists.

**Comment by navx2810** [comment]
![image](https://user-images.githubusercontent.com/3950980/27501570-3658ab20-583c-11e7-8fe2-eac12cc44370.png)

I did a quick rough of an idea for the pet card. In this instance, the card is much shorter, the next appointment is kept in it's own container, with a leading caret down to reveal more appointment details. The caret pull on the appointment div makes more semantic sense to the user. The box is big enough to be able to replace the caret with text too.

Thoughts?
_edit: I left our gender, but in reality, that can be minimized to an icon as well._

**Comment by Aphemra** [comment]
The symbol for species might get tricky if these breeders take different species other than cat and dog... But the symbol should be fine for the customer since they inherently already know what their pet is.

The side by side section like that seems a bit crowded. And correct me if I'm wrong but, will the user be required to tap "Schedule" to see what you display in the top pet card and then tap the caret for more information? That seems like one too many moves to get more details and I think from a user perspective, clicking on "Schedule", I'd expect to see all the details of the next appointment like you would get from hitting the caret.

Let me switch up the design a bit and I'll post what I get here. I'll do a few different designs to show the different states of the page so it's a bit better to understand the layout and interactivity of the design.

**Comment by Aphemra** [comment]
Here is the new design with changes and progression.
![customer-pet-section-wireframe-320x640-v2](https://user-images.githubusercontent.com/17531367/27507950-450a3130-58a9-11e7-8a24-294b4e3947cd.png)

**Comment by navx2810** [comment]
Nah. In my design above, the "schedule" was a button if no upcoming appointments were available.

I like this new design though.

I see no problems with the content at all. I'm checking this off as done.
